/*
 * This Java source file was generated by the Gradle 'init' task.
 */

//In this project we are going to create a calculator app (GUI)
// And I'm also going to implement the MVC pattern(Model-view-controller)
//Software architectural pattern for user interfaces

package com.risorlet.FXculator;

import java.io.*;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.VBox;
import javafx.scene.text.Font;
import javafx.stage.Stage;

public class App extends Application{

    @Override
    public void start(Stage primaryStage) throws Exception {

        File file = new File("F:\\Argha\\Projects\\Java\\FXculator\\app\\src\\main\\resources\\Ubuntu-Regular.ttf");
        InputStream in = new FileInputStream(file);
        Font font = Font.loadFont(in, 16);

        VBox root = new view(font);
        root.setSpacing(10);

        primaryStage.setScene(new Scene(root));
        primaryStage.setTitle("FXculator");
        primaryStage.show();
    }
    public static void main(String[] args) {
        launch();
    }
}
